version: "3.7"
services:
  api_service:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=db
      - DATABASE_PORT=3306
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        -'3306:3306'
      expose:
        # Opens port 3306 on the container
        -'3306'
        # Where our data will be persisted
      volumes:
        -my-db:/var/lib/mysql
    # Names our volume
    volumes:
        - my-db
